@baseUrl = https://cosmotown.com/api/reseller
@token = your_api_key_here
@contentType = application/json

########################################
### REGISTER (ASYNC - BULK)
########################################

###
POST {{baseUrl}}/v2/domain/register HTTP/1.1
Content-Type: {{contentType}}
x-api-key: {{token}}

{
  "items": [
    {
      "domain": "example13301.com",
      "years": 1
    },
    {
      "domain": "example13302.com",
      "years": 1,

      "ns": [
        "ndns1.cosmotown.com",
        "ndns2.cosmotown.com"
        ]
    }
  ]
}

# HTTP/1.1 200 OK
# x-ratelimit-limit: 600
# x-ratelimit-remaining: 598
# x-ratelimit-reset: 60
# content-type: application/json; charset=utf-8
# content-length: 82
# Date: Fri, 03 Apr 2026 15:44:49 GMT
# Connection: close

# {
#   "success": true,
#   "data": {
#     "validationResult": {},
#     "status": "processing",
#     "jobId": "2"
#   }
# }

########################################
### GET JOB (ASYNC - BULK)
########################################
GET {{baseUrl}}/v2/domain/register/jobs/2 HTTP/1.1
x-api-key: {{token}}

# HTTP/1.1 200 OK
# x-ratelimit-limit: 600
# x-ratelimit-remaining: 598
# x-ratelimit-reset: 60
# content-type: application/json; charset=utf-8
# content-length: 1001
# Date: Fri, 03 Apr 2026 15:45:52 GMT
# Connection: close

# {
#   "jobId": "2",
#   "state": "completed",
#   "result": [
#        {
#       "success": false,
#       "result": {
#         "code": 2302,
#         "message": "Domain already exists",
#         "description": "Command failed; object exists"
#       }
#     },
#     {
#       "success": false,
#       "result": {
#         "code": 2302,
#         "message": "Domain already exists",
#         "description": "Command failed; object exists"
#       }
#     }
#   ],
#   "createdAt": 1775231089598,
#   "processedAt": 1775231089601,
#   "finishedAt": 1775231094231
# }



